import { CookiesContextProvider } from '@fc/cookies';
import './global.css';
import { Navigation } from './(navigation)/navigation';
import { RefreshHelper } from './refresh-helper';

export const metadata = {
  title: 'Welcome to fc',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CookiesContextProvider>
          <Navigation>{children}</Navigation>
        </CookiesContextProvider>
      </body>
    </html>
  );
}
